import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/Navbar/Navbar";
import Footer from "@/components/layout/Footer/Footer";
import { Toaster } from "@/components/ui/sonner";
import CartContextProvider from "@/contexts/cartContext";
import ProvidersWrapper from "@/providers/ProvidersWrapper";

const exoFont = Exo({

  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body  className={exoFont.className}>
           
           <ProvidersWrapper>
          
              <Navbar/>

              <div className="container max-w-[1200px] mx-auto px-6 py-10">
              {children}  
              </div>

              <Toaster />
              <Footer/>
            </ProvidersWrapper>
           
     </body>
    </html>
  );
}
